version: 2.1

orbs:
  bitcart: bitcart/bitcart-shared@2

executors:
  main-executor:
    parameters:
      v:
        type: string
        default: "3.9"

    docker:
      - image: cimg/python:<< parameters.v >>

    environment:
      TEST_ARGS: "--junitxml test-results/pytest/coverage.xml --cov-report html:coverage"

commands:
  install_dependencies:
    parameters:
      cache_dir:
        type: string
        default: /home/circleci/.cache/uv

    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "~/.pyenv/version" }}-{{ checksum "uv.lock" }}

      - run:
          name: Install library
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            mkdir -p "<<parameters.cache_dir>>" && \
            uv sync --all-extras --frozen --compile-bytecode --cache-dir <<parameters.cache_dir>>
            echo ". ~/repo/.venv/bin/activate" >> $BASH_ENV
            uv cache prune --ci --cache-dir <<parameters.cache_dir>>

      - save_cache:
          paths:
            - "<<parameters.cache_dir>>"
          key: v1-dependencies-{{ .Branch }}-{{ checksum "~/.pyenv/version" }}-{{ checksum "uv.lock" }}

  upload-results:
    steps:
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: coverage

      - store_artifacts:
          path: test-results

jobs:
  test:
    parameters:
      v:
        type: string

    executor:
      name: main-executor
      v: << parameters.v >>

    environment:
      PYTHON: << parameters.v >>

    working_directory: ~/repo

    steps:
      - checkout

      - install_dependencies

      - run:
          name: run fast tests
          command: |
            make ci

      - upload-results

  deploy:
    executor: bitcart/docker-python
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      - run:
          name: upload package
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv build
            uv publish --token $PYPI_TOKEN

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - bitcart/lint:
          name: lint
      - test:
          name: test-<< matrix.v >>
          requires:
            - lint
          matrix:
            parameters:
              v:
                - "3.9"
                - "3.10"
                - "3.11"
                - "3.12"
                - "3.13"
      - deploy:
          context: global
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
